import {Student} from "../models/student.interface";

export const STUDENTS: Array<Student> = [
    {
      name: "Fabio",
      surname: "Abate",
      age: 29,
      region: "Sicilia",
      city: "Catania",
    },
    {
      name: "Alessandro",
      surname: "Candiracci",
      age: 27,
      region: "Veneto",
      city: "Padova",
    },
    {
      name: "Andrea",
      surname: "Cannavo",
      age: 26,
      region: "Piemonte",
      city: "Novara",
    },
    {
      name: "Alfredo",
      surname: "Costa",
      age: 23,
      region: "Piemonte",
      city: "Galliate",
    },
    {
      name: "Salvatore",
      surname: "Cucuzzella",
      age: 33,
      region: "Sicilia",
      city: "Vittoria",
    },
    {
      name: "Gabriele",
      surname: "Gennari",
      age: 25,
      region: "Puglia",
      city: "Brindisi",
    },
    {
      name: "Fabrizio",
      surname: "Mastroianni",
      age: 23,
      region: "Toscana",
      city: "Lucca",
    },
    {
      name: "Carla",
      surname: "Mazzeo",
      age: 22,
      region: "Campania",
      city: "Caserta",
    },
    {
      name: "Ignazio",
      surname: "Montebello",
      age: 35,
      region: "Puglia",
      city: "Bari",
    },
    {
      name: "Daniela",
      surname: "Mosquera",
      age: 24,
      region: "Lombardia",
      city: "Milano",
    },
    {
      name: "Francesca",
      surname: "Laiosa",
      age: 24,
      region: "Sicilia",
      city: "Palermo",
    },
    {
      name: "Nina Rosy",
      surname: "Kammang Djofang",
      age: 26,
      region: "Emilia Romagna",
      city: "Piacenza",
    },
    {
      name: "Laura",
      surname: "Rosa",
      age: 24,
      region: "Lombardia",
      city: "Montichiari",
    },
    {
      name: "Tiziano",
      surname: "Sapienza",
      age: 24,
      region: "Sicilia",
      city: "Catania",
    },
    {
      name: "Daniele",
      surname: "Segreto",
      age: 33,
      region: "Sicilia",
      city: "Cefalù",
    },
    {
      name: "Luca",
      surname: "Valle",
      age: 22,
      region: "Piemonte",
      city: "Torino",
    },
    {
      name: "Antonello",
      surname: "Venditti",
      age: 26,
      region: "Puglia",
      city: "Bari",
    },
  ];